# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'subgui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SubMainWindow(object):
    def setupUi(self, SubMainWindow):
        SubMainWindow.setObjectName("SubMainWindow")
        SubMainWindow.resize(700, 604)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(11)
        SubMainWindow.setFont(font)
        SubMainWindow.setToolTip("")
        SubMainWindow.setAnimated(True)
        SubMainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(SubMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.grpMain = QtWidgets.QGroupBox(self.centralwidget)
        self.grpMain.setGeometry(QtCore.QRect(-10, -20, 731, 661))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.grpMain.setFont(font)
        self.grpMain.setTitle("")
        self.grpMain.setObjectName("grpMain")
        self.grpCredits = QtWidgets.QGroupBox(self.grpMain)
        self.grpCredits.setEnabled(True)
        self.grpCredits.setGeometry(QtCore.QRect(20, 20, 331, 351))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        self.grpCredits.setFont(font)
        self.grpCredits.setAlignment(QtCore.Qt.AlignCenter)
        self.grpCredits.setObjectName("grpCredits")
        self.label = QtWidgets.QLabel(self.grpCredits)
        self.label.setGeometry(QtCore.QRect(20, 30, 291, 111))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btnGitHub = QtWidgets.QPushButton(self.grpCredits)
        self.btnGitHub.setGeometry(QtCore.QRect(20, 150, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnGitHub.setFont(font)
        self.btnGitHub.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnGitHub.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnGitHub.setAutoDefault(True)
        self.btnGitHub.setDefault(True)
        self.btnGitHub.setFlat(False)
        self.btnGitHub.setObjectName("btnGitHub")
        self.btnPatreon = QtWidgets.QPushButton(self.grpCredits)
        self.btnPatreon.setGeometry(QtCore.QRect(20, 200, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnPatreon.setFont(font)
        self.btnPatreon.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPatreon.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnPatreon.setAutoDefault(True)
        self.btnPatreon.setDefault(True)
        self.btnPatreon.setFlat(False)
        self.btnPatreon.setObjectName("btnPatreon")
        self.btnNexus = QtWidgets.QPushButton(self.grpCredits)
        self.btnNexus.setGeometry(QtCore.QRect(20, 250, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnNexus.setFont(font)
        self.btnNexus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnNexus.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnNexus.setAutoDefault(True)
        self.btnNexus.setDefault(True)
        self.btnNexus.setFlat(False)
        self.btnNexus.setObjectName("btnNexus")
        self.btnTwitter = QtWidgets.QPushButton(self.grpCredits)
        self.btnTwitter.setGeometry(QtCore.QRect(20, 300, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnTwitter.setFont(font)
        self.btnTwitter.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnTwitter.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnTwitter.setAutoDefault(True)
        self.btnTwitter.setDefault(True)
        self.btnTwitter.setFlat(False)
        self.btnTwitter.setObjectName("btnTwitter")
        self.grpPatrons = QtWidgets.QGroupBox(self.grpMain)
        self.grpPatrons.setEnabled(True)
        self.grpPatrons.setGeometry(QtCore.QRect(370, 20, 331, 351))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        self.grpPatrons.setFont(font)
        self.grpPatrons.setAlignment(QtCore.Qt.AlignCenter)
        self.grpPatrons.setObjectName("grpPatrons")
        self.lstPatrons = QtWidgets.QListWidget(self.grpPatrons)
        self.lstPatrons.setGeometry(QtCore.QRect(10, 40, 311, 301))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lstPatrons.setFont(font)
        self.lstPatrons.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lstPatrons.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.lstPatrons.setObjectName("lstPatrons")
        self.grpStatics = QtWidgets.QGroupBox(self.grpMain)
        self.grpStatics.setEnabled(True)
        self.grpStatics.setGeometry(QtCore.QRect(20, 380, 681, 231))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        self.grpStatics.setFont(font)
        self.grpStatics.setAlignment(QtCore.Qt.AlignCenter)
        self.grpStatics.setFlat(False)
        self.grpStatics.setObjectName("grpStatics")
        self.grpUDL = QtWidgets.QGroupBox(self.grpStatics)
        self.grpUDL.setEnabled(True)
        self.grpUDL.setGeometry(QtCore.QRect(20, 40, 311, 171))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        self.grpUDL.setFont(font)
        self.grpUDL.setAlignment(QtCore.Qt.AlignCenter)
        self.grpUDL.setObjectName("grpUDL")
        self.lblUDL = QtWidgets.QLabel(self.grpUDL)
        self.lblUDL.setGeometry(QtCore.QRect(10, 40, 291, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(33)
        self.lblUDL.setFont(font)
        self.lblUDL.setAlignment(QtCore.Qt.AlignCenter)
        self.lblUDL.setObjectName("lblUDL")
        self.grpTDL = QtWidgets.QGroupBox(self.grpStatics)
        self.grpTDL.setEnabled(True)
        self.grpTDL.setGeometry(QtCore.QRect(350, 40, 311, 171))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        self.grpTDL.setFont(font)
        self.grpTDL.setAlignment(QtCore.Qt.AlignCenter)
        self.grpTDL.setObjectName("grpTDL")
        self.lblTDL = QtWidgets.QLabel(self.grpTDL)
        self.lblTDL.setGeometry(QtCore.QRect(10, 40, 291, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(33)
        self.lblTDL.setFont(font)
        self.lblTDL.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTDL.setObjectName("lblTDL")
        SubMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SubMainWindow)
        QtCore.QMetaObject.connectSlotsByName(SubMainWindow)

    def retranslateUi(self, SubMainWindow):
        _translate = QtCore.QCoreApplication.translate
        SubMainWindow.setWindowTitle(_translate("SubMainWindow", "Credits"))
        self.grpCredits.setTitle(_translate("SubMainWindow", "Credits"))
        self.label.setText(_translate("SubMainWindow", "<html><head/><body><p>Coded by</p><p><span style=\" font-weight:600;\">Khaled El-Morshedy</span></p><p>(elmoiv)</p></body></html>"))
        self.btnGitHub.setText(_translate("SubMainWindow", "GitHub"))
        self.btnPatreon.setText(_translate("SubMainWindow", "Patreon"))
        self.btnNexus.setText(_translate("SubMainWindow", "Nexus Mods"))
        self.btnTwitter.setText(_translate("SubMainWindow", "Twitter"))
        self.grpPatrons.setTitle(_translate("SubMainWindow", "Premium Patrons"))
        self.grpStatics.setTitle(_translate("SubMainWindow", "Statistics"))
        self.grpUDL.setTitle(_translate("SubMainWindow", "Unique Downloads"))
        self.lblUDL.setText(_translate("SubMainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.grpTDL.setTitle(_translate("SubMainWindow", "Total Downloads"))
        self.lblTDL.setText(_translate("SubMainWindow", "<html><head/><body><p><br/></p></body></html>"))
